export const handleError = (error: any) => {
  console.log("=".repeat(40));
  console.log("‚ùå Error occurred while fetching data.");
  console.log(error);
  console.log("=".repeat(40));
};
